[window]
decorations = "None"
padding.x = 5
padding.y = 5
dynamic_padding = true

[colors.primary]
foreground = "#E0E0E0"
background = "#021E20"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "Maple Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 11.25
 
[cursor]
style.shape = "Underline"
style.blinking = "Always"
blink_interval = 500
blink_timeout = 10

[selection]
save_to_clipboard = true

[debug]
log_level = "Warn"
